language: node_js
node_js:
  - "10.10.0"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run test
  - yarn run build

deploy:
  local-dir: build
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
